spring:
  ai:
    mcp:
      server:
        name: poop-mcp-server
        version: 0.0.1
server:
  port: 8888
coingecko:
  api:
    key: ${COINGECKO_API_KEY}
    url: https://api.coingecko.com
hyperAGI:
  api: ${HYPER_AGI_API}